---

- hosts: "{{ host }}"
  tasks:
    - name: install oauth2-proxy
      register: monitoring
      kubernetes.core.helm:
        name: monitoring
        chart_ref: prometheus-community
        chart_repo_url: https://prometheus-community.github.io/helm-charts
        wait: true
        values:
        
          
   
    - debug:
        msg: "{{ monitoring.stdout_lines }}"
