- name: download k3s
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: 0755
    force: true

- name: run  k3s install
  command: "/tmp/k3s_install.sh --write-kubeconfig-mode 644 --disable traefik --disable servicelb"
  register: k3s
  environment: 
    INSTALL_K3S_VERSION: "{{ k3s_version }}"

- name: create .kube directory
  file:
    path: "{{ item.file }}"
    state: directory
    mode: 0755
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
  with_items:
    - {file: "~/.kube", user: "root"} 
    - {file: "/home/{{ ansible_user }}/.kube", user: "{{ ansible_user }}"}

- name: copy kubectl config
  copy:
    src: /etc/rancher/k3s/k3s.yaml 
    dest: "{{ item.file }}"
    remote_src: yes
    mode: 0600
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
  with_items:
    - {file: "~/.kube/config", user: "root"} 
    - {file: "/home/{{ ansible_user }}/.kube/config", user: "{{ ansible_user }}"}

- debug:
    msg: "{{ k3s.stdout_lines }}"
