---
- name: Update all packages
  apt:
    upgrade: full
    update_cache: yes
  register: update
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- debug:
    msg: "{{ update.stdout_lines }}"
