- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  with_items: 
    - {name: 'longhorn', url: 'https://charts.longhorn.io'}

- name: Deploy longhorn
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    create_namespace: true
    update_repo_cache: true
    chart_version: 1.4.0
    wait: true
    values:
      persistence:
        defaultClassReplicaCount: 1
